"""Shared Squidle data I/O for bots, COCO export, and evaluation tooling."""

from squidle_data.api import (
    ANNOTATION_EXPORT_COLUMNS,
    ANNOTATION_SET_EXPORT_COLUMNS,
    EXPORT_COLUMNS,
    MEDIA_EXPORT_COLUMNS,
    connect_sqapi,
    export_endpoint_to_df,
    get_media_collection_id,
    load_squidle_annotation_set_and_media,
    load_squidle_annotations_to_df,
    load_squidle_media_collection_to_df,
)
from squidle_data.coco import build_coco_from_squidle_annotations, categories_from_annotation_df
from squidle_data.columns import (
    COL_COLLECTION_ID,
    COL_FILE_NAME,
    COL_IMAGE_ID,
    COL_LABEL_ID,
    COL_LABEL_NAME,
    COL_PIXEL_HEIGHT,
    COL_PIXEL_WIDTH,
    COL_POINT_MEDIA_ID,
    COL_POINT_MEDIA_KEY,
    COL_POINT_MEDIA_PATH,
    COL_POINT_POLYGON,
    COL_POINT_X,
    COL_POINT_Y,
    COL_URI,
)
from squidle_data.geometry import (
    COL_LIKELIHOOD,
    append_exemplar_geometry,
    parse_polygon_rel,
    squidle_offsets_to_norm_vertices,
)
from squidle_data.cache import (
    cache_path_for_url,
    fetch_url_to_cache,
    image_size_from_uri,
    is_remote_uri,
    open_pil_from_uri_or_path,
    resolve_image_cache_dir,
)
from squidle_data.tables import (
    clean_export_columns,
    file_name_from_uri,
    load_table,
    media_size_lookup_from_collection_df,
    normalize_squidle_collection_df,
)

__all__ = [
    "ANNOTATION_EXPORT_COLUMNS",
    "ANNOTATION_SET_EXPORT_COLUMNS",
    "COL_COLLECTION_ID",
    "COL_FILE_NAME",
    "COL_IMAGE_ID",
    "COL_LABEL_ID",
    "COL_LABEL_NAME",
    "COL_LIKELIHOOD",
    "COL_PIXEL_HEIGHT",
    "COL_PIXEL_WIDTH",
    "COL_POINT_MEDIA_ID",
    "COL_POINT_MEDIA_KEY",
    "COL_POINT_MEDIA_PATH",
    "COL_POINT_POLYGON",
    "COL_POINT_X",
    "COL_POINT_Y",
    "COL_URI",
    "EXPORT_COLUMNS",
    "MEDIA_EXPORT_COLUMNS",
    "append_exemplar_geometry",
    "build_coco_from_squidle_annotations",
    "cache_path_for_url",
    "categories_from_annotation_df",
    "clean_export_columns",
    "connect_sqapi",
    "export_endpoint_to_df",
    "fetch_url_to_cache",
    "file_name_from_uri",
    "get_media_collection_id",
    "image_size_from_uri",
    "is_remote_uri",
    "load_squidle_annotation_set_and_media",
    "load_squidle_annotations_to_df",
    "load_squidle_media_collection_to_df",
    "load_table",
    "media_size_lookup_from_collection_df",
    "normalize_squidle_collection_df",
    "open_pil_from_uri_or_path",
    "parse_polygon_rel",
    "resolve_image_cache_dir",
    "squidle_offsets_to_norm_vertices",
]
